trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK'
  inputs:
    version: 2.2.100	
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'RemiBou.Blazor.DataAnnotation/*.csproj'
    versioningScheme: byPrereleaseNumber
    majorVersion: '0'
    minorVersion: '0'
    patchVersion: '0'
    configuration: '$(buildConfiguration)'
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget'
    versioningScheme: byPrereleaseNumber
    majorVersion: '0'
    minorVersion: '0'
    patchVersion: '0'
    verbosityPush: 'Detailed'
    configuration: '$(buildConfiguration)'
