trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK'
  inputs:
    version: 2.2.100	
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.2' 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: RemiBou.Blazor.DataAnnotation/RemiBou.Blazor.DataAnnotation.csproj
    versioningScheme: byBuildNumber
- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push

    nuGetFeedType: external

    publishFeedCredentials: Nuget

    versioningScheme: byBuildNumber

