trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  projectName: 'Blazor.RemiBou.DataAnnotation'
  packageVersion: '0.0.$(Build.BuildId)'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK'
  inputs:
    version: 2.2.100	
- script: dotnet pack $(projectName)/$(projectName).nuspec --configuration $(buildConfiguration) -p:PackageVersion=$(packageVersion)
  displayName: 'dotnet pack'
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget'
    versioningScheme: byEnvVar
    versionEnvVar: Version
